#!/usr/bin/env bash
#commands to install nginx on the web server

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo "Hello world!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx reload
