#!/usr/bin/env bash
#Performing 301 Moved Permanently Redirection

#Update and install nginx 
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"this code 

#Create index.html homepage
echo "Hello World!" | sudo tee /var/www/html/index.html

#Redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/saviour99 permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#Test nginx 
sudo nginx -t

#Restart Nginx
sudo service nginx restart
