#!/usr/bin/env bash
#Customised 404 Page

#Update and install nginx 
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"this code 

#Create index.html homepage
echo "Hello World!" | sudo tee /var/www/html/index.html

#Redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/saviour99 permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#Creating 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default

#Test nginx 
sudo nginx -t

#Restart Nginx
sudo service nginx restart
