#!/usr/bin/env bash
#Bash script that configure Nginx to run and listen on port 80 of all the servers
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
