#!/usr/bin/env bash
#Bash script that accepts one argument

#Checks if an argument exist when the code is run
if [ -z "$1" ];
then
	echo "Please provide a user as an argument."
	exit 1
fi

# Runs the 'whoami' command under the user passed as an argument
su "$1" -c "whoami"
